-- MIGRATION: Fix Referral Network and Consolidate Registration Trigger
-- Este script unifica a lógica de cadastro e garante que indicações funcionem independente de maiúsculas/minúsculas.

-- 1. Garantir que a tabela de logs de debug exista
CREATE TABLE IF NOT EXISTS public.debug_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation text,
    message text,
    metadata jsonb,
    created_at timestamp with time zone DEFAULT now()
);

-- 2. Função de Trigger Consolidada e Robusta
CREATE OR REPLACE FUNCTION public.handle_new_affiliate_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
 AS $function$
 DECLARE
   v_full_name text;
   v_sponsor_id uuid;
   v_org_id uuid;
   v_sponsor_code text;
   v_error_msg text;
 BEGIN
   -- A. Log de Entrada para Depuração
   INSERT INTO public.debug_logs (operation, message, metadata) 
   VALUES ('signup_start', 'Iniciando processamento de novo usuário: ' || new.email, new.raw_user_meta_data);

   -- B. Determinar Nome Completo
   v_full_name := TRIM(CONCAT_WS(' ', 
     new.raw_user_meta_data ->> 'nome', 
     new.raw_user_meta_data ->> 'sobrenome'
   ));
   
   IF v_full_name = '' THEN
     v_full_name := 'Novo Afiliado';
   END IF;

   -- C. Determinar Organização (Multi-tenant)
   BEGIN
     v_org_id := (new.raw_user_meta_data ->> 'organization_id')::uuid;
   EXCEPTION WHEN OTHERS THEN
     v_org_id := NULL;
   END;

   -- Fallback para "Classe A" se não vier no metadata
   IF v_org_id IS NULL THEN
      SELECT id INTO v_org_id FROM public.organizations WHERE name = 'Classe A' LIMIT 1;
   END IF;

   -- D. Resolver ID do Padrinho (Sponsor) usando busca CASE-INSENSITIVE
   v_sponsor_code := NULLIF(new.raw_user_meta_data ->> 'sponsor_code', '');
   
   IF v_sponsor_code IS NOT NULL THEN
     -- Buscamos pelo referral_code ignorando maiúsculas/minúsculas
     SELECT id INTO v_sponsor_id 
     FROM public.affiliates 
     WHERE LOWER(referral_code) = LOWER(v_sponsor_code)
     AND organization_id = v_org_id
     LIMIT 1;

     IF v_sponsor_id IS NULL THEN
        INSERT INTO public.debug_logs (operation, message, metadata) 
        VALUES ('signup_warning', 'Padrinho não encontrado para o código: ' || v_sponsor_code, new.raw_user_meta_data);
     END IF;
   END IF;

   -- E. Criar Perfil do Usuário
   BEGIN
     INSERT INTO public.user_profiles (
       id, email, role, cpf, cnpj, registration_type, 
       organization_id, sponsor_id, created_at, updated_at
     )
     VALUES (
       new.id, 
       new.email, 
       COALESCE(new.raw_user_meta_data ->> 'role', 'affiliate'),
       new.raw_user_meta_data ->> 'cpf',
       new.raw_user_meta_data ->> 'cnpj',
       new.raw_user_meta_data ->> 'registration_type',
       v_org_id,
       v_sponsor_id,
       new.created_at, 
       new.created_at
     );
   EXCEPTION WHEN OTHERS THEN
     GET STACKED DIAGNOSTICS v_error_msg = MESSAGE_TEXT;
     INSERT INTO public.debug_logs (operation, message, metadata) 
     VALUES ('signup_error_profile', v_error_msg, new.raw_user_meta_data);
     RAISE EXCEPTION 'Erro ao criar perfil: %', v_error_msg;
   END;

   -- F. Criar Registro de Afiliado
   BEGIN
     INSERT INTO public.affiliates (
       user_id, email, full_name, referral_code, cpf, cnpj, whatsapp, 
       organization_id, sponsor_id, is_active, created_at, updated_at
     )
     VALUES (
       new.id,
       new.email,
       v_full_name,
       new.raw_user_meta_data ->> 'login', -- O login do usuário se torna seu código de indicação
       new.raw_user_meta_data ->> 'cpf',
       new.raw_user_meta_data ->> 'cnpj',
       new.raw_user_meta_data ->> 'whatsapp',
       v_org_id,
       v_sponsor_id,
       true, -- Afiliados novos começam ativos por padrão
       new.created_at,
       new.updated_at
     );
   EXCEPTION WHEN OTHERS THEN
     GET STACKED DIAGNOSTICS v_error_msg = MESSAGE_TEXT;
     INSERT INTO public.debug_logs (operation, message, metadata) 
     VALUES ('signup_error_affiliate', v_error_msg, new.raw_user_meta_data);
     RAISE EXCEPTION 'Erro ao criar afiliado: %', v_error_msg;
   END;

   -- G. Criar Configurações Iniciais (Carteira, etc)
   BEGIN
     INSERT INTO public.user_settings (user_id, organization_id, created_at, updated_at)
     VALUES (new.id, v_org_id, new.created_at, new.created_at);
   EXCEPTION WHEN OTHERS THEN
     -- Ignoramos erro no settings para não travar o cadastro principal
     NULL;
   END;
   
   RETURN new;
 END;
 $function$;

-- 3. Recriar o Trigger para garantir o vínculo correto
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_affiliate_user();

-- 4. Notificar Sucesso no Log
INSERT INTO public.debug_logs (operation, message) VALUES ('migration_success', 'Trigger de cadastro unificado e corrigido (case-insensitive).');
